### PR TITLE
Decorate class

### PR DESCRIPTION
**Pull request by Said-laasri**
**Created a class Nameable.**
```
Implement a method called correct_name that will raise a NotImplementedError.

```
**Turn Person class to Nameable**
```
Person class inherits from Nameable
class has a method correct_name implemented. It should simply return the name attribute.
```
**Prepare base Decorator**

```
inherits from Nameable.
assign a nameable object from params to an instance variable In the constructor.
correct_name method returns the result of the correct_name method of the @nameable.
```
**CapitalizeDecorator and TrimmerDecorator**

1. For the CapitalizeDecorator:

- Created a class that inherits from the base Decorator class.
- Implemented a method correct_name that capitalizes the output of @nameable.correct_name.

2. For the TrimmerDecorator:

- Created a class that inherits from the base Decorator class.
- Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

**decorators in action**
```

person = Person.new(22, 'maximilianus')
  person.correct_name
  capitalizedPerson = CapitalizeDecorator.new(person)
  capitalizedPerson.correct_name
  capitalizedTrimmedPerson = TrimmerDecorator.new(capitalizedPerson)
  capitalizedTrimmedPerson.correct_name
```

### CODE REVIEW

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Said-laasri,

Good job so far!
✔️ Good implementation of inheritance to decorate class
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Your README title is describing the previous enumerable project whereas this is a school library project. Kindly fix your title to be more descriptive of the project

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Said-laasri** [comment]
@TedLivist  Thank you for reviewing my project, I will make the necessary corrections as suggested

**Review by gemmen29 — APPROVED** [review]
Hi @Said-laasri, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 



## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Said-laasri** [comment]
@gemmen29  Thank you for reviewing my project

**Pull request merged**
